import { tags as t } from "@lezer/highlight";
import { createTheme } from "@uiw/codemirror-themes";
import { useTheme } from "@/stores/theme";

/* ─── Light theme (Apple-inspired, maps to CSS tokens) ─── */

export const piLightTheme = createTheme({
	theme: "light",
	settings: {
		background: "#ffffff",
		foreground: "#111111",
		caret: "#5b5bf7",
		selection: "#ececff",
		selectionMatch: "#ececff",
		gutterBackground: "#f5f5f7",
		gutterForeground: "#999999",
		gutterActiveForeground: "#111111",
		lineHighlight: "rgba(0,0,0,0.04)",
	},
	styles: [
		{ tag: t.comment, color: "#999999" },
		{ tag: t.lineComment, color: "#999999" },
		{ tag: t.blockComment, color: "#999999" },
		{ tag: t.docComment, color: "#999999" },
		{ tag: t.keyword, color: "#5b5bf7" },
		{ tag: t.controlKeyword, color: "#5b5bf7" },
		{ tag: t.operatorKeyword, color: "#5b5bf7" },
		{ tag: t.definitionKeyword, color: "#5b5bf7" },
		{ tag: t.self, color: "#5b5bf7" },
		{ tag: t.bool, color: "#5b5bf7" },
		{ tag: t.null, color: "#999999" },
		{ tag: t.number, color: "#ff9f0a" },
		{ tag: t.integer, color: "#ff9f0a" },
		{ tag: t.float, color: "#ff9f0a" },
		{ tag: t.string, color: "#34c759" },
		{ tag: t.special(t.string), color: "#34c759" },
		{ tag: t.regexp, color: "#ff3b30" },
		{ tag: t.escape, color: "#5b5bf7" },
		{ tag: t.variableName, color: "#111111" },
		{ tag: t.function(t.variableName), color: "#5b5bf7" },
		{ tag: t.definition(t.variableName), color: "#111111" },
		{ tag: t.className, color: "#5b5bf7" },
		{ tag: t.typeName, color: "#5b5bf7" },
		{ tag: t.propertyName, color: "#111111" },
		{ tag: t.definition(t.propertyName), color: "#5b5bf7" },
		{ tag: t.operator, color: "#666666" },
		{ tag: t.punctuation, color: "#666666" },
		{ tag: t.bracket, color: "#666666" },
		{ tag: t.angleBracket, color: "#666666" },
		{ tag: t.squareBracket, color: "#666666" },
		{ tag: t.paren, color: "#666666" },
		{ tag: t.brace, color: "#666666" },
		{ tag: t.separator, color: "#666666" },
		{ tag: t.special(t.propertyName), color: "#5b5bf7" },
		{ tag: t.tagName, color: "#5b5bf7" },
		{ tag: t.attributeName, color: "#ff9f0a" },
		{ tag: t.attributeValue, color: "#34c759" },
		{ tag: t.heading, color: "#111111", fontWeight: "500" },
		{ tag: t.link, color: "#5b5bf7" },
		{ tag: t.emphasis, fontStyle: "italic" },
		{ tag: t.strong, fontWeight: "600" },
		{ tag: t.strikethrough, textDecoration: "line-through" },
		{ tag: t.processingInstruction, color: "#999999" },
		{ tag: t.content, color: "#111111" },
		{ tag: t.contentSeparator, color: "#999999" },
		{ tag: t.list, color: "#5b5bf7" },
		{ tag: t.quote, color: "#999999" },
		{ tag: t.monospace, color: "#111111" },
	],
});

/* ─── Dark theme (Apple-inspired, maps to dark CSS tokens) ─── */

export const piDarkTheme = createTheme({
	theme: "dark",
	settings: {
		background: "#2c2c2e",
		foreground: "#f5f5f7",
		caret: "#7b7bff",
		selection: "rgba(123,123,255,0.15)",
		selectionMatch: "rgba(123,123,255,0.15)",
		gutterBackground: "#1c1c1e",
		gutterForeground: "#98989d",
		gutterActiveForeground: "#f5f5f7",
		lineHighlight: "rgba(255,255,255,0.06)",
	},
	styles: [
		{ tag: t.comment, color: "#98989d" },
		{ tag: t.lineComment, color: "#98989d" },
		{ tag: t.blockComment, color: "#98989d" },
		{ tag: t.docComment, color: "#98989d" },
		{ tag: t.keyword, color: "#7b7bff" },
		{ tag: t.controlKeyword, color: "#7b7bff" },
		{ tag: t.operatorKeyword, color: "#7b7bff" },
		{ tag: t.definitionKeyword, color: "#7b7bff" },
		{ tag: t.self, color: "#7b7bff" },
		{ tag: t.bool, color: "#7b7bff" },
		{ tag: t.null, color: "#98989d" },
		{ tag: t.number, color: "#ffd60a" },
		{ tag: t.integer, color: "#ffd60a" },
		{ tag: t.float, color: "#ffd60a" },
		{ tag: t.string, color: "#30d158" },
		{ tag: t.special(t.string), color: "#30d158" },
		{ tag: t.regexp, color: "#ff453a" },
		{ tag: t.escape, color: "#7b7bff" },
		{ tag: t.variableName, color: "#f5f5f7" },
		{ tag: t.function(t.variableName), color: "#7b7bff" },
		{ tag: t.definition(t.variableName), color: "#f5f5f7" },
		{ tag: t.className, color: "#7b7bff" },
		{ tag: t.typeName, color: "#7b7bff" },
		{ tag: t.propertyName, color: "#f5f5f7" },
		{ tag: t.definition(t.propertyName), color: "#7b7bff" },
		{ tag: t.operator, color: "#98989d" },
		{ tag: t.punctuation, color: "#98989d" },
		{ tag: t.bracket, color: "#98989d" },
		{ tag: t.angleBracket, color: "#98989d" },
		{ tag: t.squareBracket, color: "#98989d" },
		{ tag: t.paren, color: "#98989d" },
		{ tag: t.brace, color: "#98989d" },
		{ tag: t.separator, color: "#98989d" },
		{ tag: t.special(t.propertyName), color: "#7b7bff" },
		{ tag: t.tagName, color: "#7b7bff" },
		{ tag: t.attributeName, color: "#ffd60a" },
		{ tag: t.attributeValue, color: "#30d158" },
		{ tag: t.heading, color: "#f5f5f7", fontWeight: "500" },
		{ tag: t.link, color: "#7b7bff" },
		{ tag: t.emphasis, fontStyle: "italic" },
		{ tag: t.strong, fontWeight: "600" },
		{ tag: t.strikethrough, textDecoration: "line-through" },
		{ tag: t.processingInstruction, color: "#98989d" },
		{ tag: t.content, color: "#f5f5f7" },
		{ tag: t.contentSeparator, color: "#98989d" },
		{ tag: t.list, color: "#7b7bff" },
		{ tag: t.quote, color: "#98989d" },
		{ tag: t.monospace, color: "#f5f5f7" },
	],
});

/** Returns the appropriate CodeMirror theme based on the current app theme. */
export function useCmTheme() {
	const { applied } = useTheme();
	return applied === "dark" ? piDarkTheme : piLightTheme;
}
